name: Send daily email

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # run every midnight

jobs:
  build:
    runs-on: ubuntu-latest

    env:  # setup env
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      PORT: ${{ secrets.PORT }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}  # get GitHub secrets into env

    steps:
      - uses: actions/checkout@v4  # check out repo so a workflow can access it

      - uses: actions/setup-node@v4.0.2

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.2.1

      - name: Check poetry version
        run: poetry --version

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.5.0
        with:
          chrome-version: 120

      - name: Install dependencies and run main.py
        run: |
          poetry install && poetry run python main.py
