name: Send daily email

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # be able to run manually on GitHub
  schedule:
    - cron: "0 0 * * *"  # run every midnight

jobs:
  build:
    runs-on: ubuntu-latest  # most current os

    env:  # setup env
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      PORT: ${{ secrets.PORT }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}  # get GitHub secrets into env

    steps:
      - uses: actions/checkout@v3  # check out repo so a workflow can access it

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4  # sets up a python environment
        with:
          python-version: '3.11'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.1
        run: poetry --version

      - name: Setup Chrome
        Uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
        run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: Install dependencies and run main.py
        run: |
          poetry install && poetry run python main.py
