name: send daily email

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # check out repo so a workflow can access it
      - name: Set up Python
        uses: actions/setup-python@v2  # sets up a python environment
        with:
          python-version: '3.8'
      - name: Prepare Firefox
        uses: browser-actions/setup-firefox@latest
      - name: Firefox version
        run: firefox --version
      - name: Install dependencies and send email
        env:  # setup env
          PASSWORD: ${{ secrets.PASSWORD }}  # get GitHub secrets into env
        run: |  # install dependencies and run main.py
          pip install -r requirements.txt  
          python main.py



#          steps:
#            - name: Hello world action
#              with: # Set the secret as an input
#                password: ${{ secrets.PASSWORD }}