name: send daily email

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # check out repo so a workflow can access it
      - name: Set up Python
        uses: actions/setup-python@v2  # sets up a python environment
        with:
          python-version: '3.8'
      - name: Install dependencies and send email
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv run python main.py
        with:
          password: ${{ secrets.PASSWORD }}