name: send daily email

on:
  workflow_dispatch:  # be able to run manually on GitHub
  schedule:
    - cron: "0 0 * * *"  # run every midnight

jobs:
  build:
    runs-on: ubuntu-latest  # most current os

    steps:
      - uses: actions/checkout@v2  # check out repo so a workflow can access it
      - name: Set up Python
        uses: actions/setup-python@v2  # sets up a python environment
        with:
          python-version: '3.8'
      - name: Prepare Firefox
        uses: browser-actions/setup-firefox@latest  # install firefox
      - name: Firefox version  # check if firefox is installed
        run: firefox --version
      - name: Install dependencies and send email
        env:  # setup env
          PASSWORD: ${{ secrets.PASSWORD }}  # get GitHub secrets into env
        run: |  # install dependencies and run main.py
          pip install -r requirements.txt
          python main.py