name: send daily email

on:
  workflow_dispatch:  # be able to run manually on GitHub
  schedule:
    - cron: "0 0 * * *"  # run every midnight

jobs:
  build:
    runs-on: ubuntu-latest  # most current os

    steps:
      - uses: actions/checkout@v3  # check out repo so a workflow can access it

      - name: Set up Python
        uses: actions/setup-python@v4  # sets up a python environment
        with:
          python-version: '3.10'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.1

#      - name: Install poetry
#        uses: abatilo/actions-poetry@v2
#        with:
#          poetry-version: '1.2.1'

#      - name: Poetry version  # check poetry version
#        run: poetry --version

#      - name: Prepare Chrome
#        uses: browser-actions/setup-chrome
#        with:
#          chrome-version: '106.0.5249'  # install specific version of chrome

#      - name: Chrome version  # check if chrome is installed
#        run: chrome --version

#      - name: Install dependencies and send email
#        env:  # setup env
#          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
#          PORT: ${{ secrets.PORT }}
#          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
#          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
#          PASSWORD: ${{ secrets.PASSWORD }}  # get GitHub secrets into env

#      - name: Install dependencies and run main.py
#        run: |
#          python -m poetry install
#          python main.py