name: Send daily email

on:
  workflow_dispatch:  # be able to run manually on GitHub
  schedule:
    - cron: "0 0 * * *"  # run every midnight

jobs:
  build:
    runs-on: ubuntu-latest  # most current os

    env:  # setup env
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      PORT: ${{ secrets.PORT }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}  # get GitHub secrets into env

    steps:
      - uses: actions/checkout@v3  # check out repo so a workflow can access it

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4  # sets up a python environment
        with:
          python-version: '3.10'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.1

      - name: Poetry version  # check poetry version
        run: poetry --version

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 106.0.5249.103  # install specific version of chrome

      - name: Chrome version  # check if chrome is installed
        run: chrome --version

#      - name: Setup env with environment variables
#        env:  # setup env
#          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
#          PORT: ${{ secrets.PORT }}
#          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
#          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
#          PASSWORD: ${{ secrets.PASSWORD }}  # get GitHub secrets into env

#      - name: Install dependencies and run main.py
#        run: |
#          python -m poetry install
#          python main.py
#          poetry install
#          poetry run python main.py